# An Intuitive Introduction Of Word2Vec By Building A Word2Vec From Scratch

In [1]:
import numpy as np

Define the sentences of interest.

In [2]:
docs = ["I like watching movie", "I enjoy watching movie"]

In [3]:
docs[0][0].split()

['I']

Create the one-hot encoded version of each sentence.

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=0, token_pattern=r"\b\w+\b")
vectorizer.fit(docs)

print(vectorizer.vocabulary_)
# encode document
vector = vectorizer.transform(docs)
# summarize encoded vector
print(vector.shape)
print(type(vector))
print(vector.toarray())

{'i': 1, 'like': 2, 'watching': 4, 'movie': 3, 'enjoy': 0}
(2, 5)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 1 1 1 1]
 [1 1 0 1 1]]


In [5]:
print(vectorizer.vocabulary_)
print(vector.shape)
print(vector.toarray())

{'i': 1, 'like': 2, 'watching': 4, 'movie': 3, 'enjoy': 0}
(2, 5)
[[0 1 1 1 1]
 [1 1 0 1 1]]


Create the input and the output dataset.

In [6]:
x = []
y = []
for i in range(len(docs)):
    for j in range(len(docs[i].split())):
        t_x = []
        t_y = []
        for k in range(4):
            if(j==k):
                t_y.append(docs[i].split()[k])
                continue
            else:
                t_x.append(docs[i].split()[k])
        x.append(t_x)
        y.append(t_y)

In [7]:
x

[['like', 'watching', 'movie'],
 ['I', 'watching', 'movie'],
 ['I', 'like', 'movie'],
 ['I', 'like', 'watching'],
 ['enjoy', 'watching', 'movie'],
 ['I', 'watching', 'movie'],
 ['I', 'enjoy', 'movie'],
 ['I', 'enjoy', 'watching']]

In [8]:
y

[['I'],
 ['like'],
 ['watching'],
 ['movie'],
 ['I'],
 ['enjoy'],
 ['watching'],
 ['movie']]

In [9]:
x2 = []
y2 = []
for i in range(len(x)):
    x2.append(' '.join(x[i]))
    y2.append(' '.join(y[i]))

In [10]:
x2

['like watching movie',
 'I watching movie',
 'I like movie',
 'I like watching',
 'enjoy watching movie',
 'I watching movie',
 'I enjoy movie',
 'I enjoy watching']

In [11]:
y2

['I', 'like', 'watching', 'movie', 'I', 'enjoy', 'watching', 'movie']

Transform the preceding input and output words into vectors.

In [12]:
vector_x = vectorizer.transform(x2)
vector_x.toarray()

array([[0, 0, 1, 1, 1],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0],
       [1, 1, 0, 0, 1]], dtype=int64)

In [13]:
vector_y = vectorizer.transform(y2)
vector_y.toarray()

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0]], dtype=int64)

In [14]:
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM , Bidirectional,Dropout
from keras import backend as K
from keras.layers.advanced_activations import LeakyReLU
from keras import regularizers

Using TensorFlow backend.


Define the neural network model that maps the input and output vector with a hidden layer that has three units.

In [15]:
model = Sequential()
model.add(Dense(3, activation='linear', input_shape=(5,)))
model.add(Dense(5,activation='sigmoid'))
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 18        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 20        
Total params: 38
Trainable params: 38
Non-trainable params: 0
_________________________________________________________________


Compile and fit the model.

In [16]:
model.compile(loss='binary_crossentropy',optimizer='adam')
model.fit(vector_x, vector_y, epochs=1000, batch_size=4,verbose=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
8/8 [==============================] - 0s 58ms/step - loss: 0.9429
Epoch 2/1000
8/8 [==============================] - 0s 748us/step - loss: 0.9385
Epoch 3/1000
8/8 [==============================] - 0s 997us/step - loss: 0.9330
Epoch 4/1000
8/8 [==============================] - 0s 748us/step - loss: 0.9279
Epoch 5/1000
8/8 [==============================] - 0s 873us/step - loss: 0.9233
Epoch 6/1000
8/8 [==============================] - 0s 873us/step - loss: 0.9182
Epoch 7/1000
8/8 [==============================] - 0s 621us/step - loss: 0.9132
Epoch 8/1000
8/8 [==============================] - 0s 1ms/step - loss: 0.9083
Epoch 9/1000
8/8 [==============================] - 0s 623us/step - loss: 0.9034
Epoch 10/1000
8/8 [==============================] - 0s 997us/step - loss: 0.8983
Epoch 11/1000
8/8 [==============================] - 0s 1ms/step - loss: 0.8937
Epoch 12/1000
8/8 [==============================] - 0s 748us/st

8/8 [==============================] - 0s 748us/step - loss: 0.6442
Epoch 98/1000
8/8 [==============================] - 0s 873us/step - loss: 0.6421
Epoch 99/1000
8/8 [==============================] - 0s 873us/step - loss: 0.6404
Epoch 100/1000
8/8 [==============================] - 0s 748us/step - loss: 0.6388
Epoch 101/1000
8/8 [==============================] - 0s 873us/step - loss: 0.6369
Epoch 102/1000
8/8 [==============================] - 0s 748us/step - loss: 0.6349
Epoch 103/1000
8/8 [==============================] - 0s 997us/step - loss: 0.6334
Epoch 104/1000
8/8 [==============================] - 0s 623us/step - loss: 0.6315
Epoch 105/1000
8/8 [==============================] - 0s 748us/step - loss: 0.6299
Epoch 106/1000
8/8 [==============================] - 0s 623us/step - loss: 0.6281
Epoch 107/1000
8/8 [==============================] - 0s 748us/step - loss: 0.6265
Epoch 108/1000
8/8 [==============================] - 0s 748us/step - loss: 0.6248
Epoch 109/1000
8/8 [=

8/8 [==============================] - 0s 748us/step - loss: 0.5224
Epoch 197/1000
8/8 [==============================] - 0s 748us/step - loss: 0.5217
Epoch 198/1000
8/8 [==============================] - 0s 873us/step - loss: 0.5209
Epoch 199/1000
8/8 [==============================] - 0s 748us/step - loss: 0.5202
Epoch 200/1000
8/8 [==============================] - 0s 748us/step - loss: 0.5194
Epoch 201/1000
8/8 [==============================] - 0s 623us/step - loss: 0.5188
Epoch 202/1000
8/8 [==============================] - 0s 1ms/step - loss: 0.5179
Epoch 203/1000
8/8 [==============================] - 0s 748us/step - loss: 0.5173
Epoch 204/1000
8/8 [==============================] - 0s 748us/step - loss: 0.5166
Epoch 205/1000
8/8 [==============================] - 0s 873us/step - loss: 0.5160
Epoch 206/1000
8/8 [==============================] - 0s 748us/step - loss: 0.5153
Epoch 207/1000
8/8 [==============================] - 0s 873us/step - loss: 0.5146
Epoch 208/1000
8/8 [=

8/8 [==============================] - 0s 748us/step - loss: 0.4726
Epoch 295/1000
8/8 [==============================] - 0s 872us/step - loss: 0.4722
Epoch 296/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4719
Epoch 297/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4715
Epoch 298/1000
8/8 [==============================] - 0s 873us/step - loss: 0.4711
Epoch 299/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4708
Epoch 300/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4704
Epoch 301/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4701
Epoch 302/1000
8/8 [==============================] - 0s 997us/step - loss: 0.4697
Epoch 303/1000
8/8 [==============================] - 0s 997us/step - loss: 0.4694
Epoch 304/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4690
Epoch 305/1000
8/8 [==============================] - 0s 873us/step - loss: 0.4687
Epoch 306/1000
8/8 

8/8 [==============================] - 0s 748us/step - loss: 0.4403
Epoch 394/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4400
Epoch 395/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4397
Epoch 396/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4394
Epoch 397/1000
8/8 [==============================] - 0s 997us/step - loss: 0.4391
Epoch 398/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4388
Epoch 399/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4385
Epoch 400/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4382
Epoch 401/1000
8/8 [==============================] - 0s 623us/step - loss: 0.4378
Epoch 402/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4375
Epoch 403/1000
8/8 [==============================] - 0s 873us/step - loss: 0.4372
Epoch 404/1000
8/8 [==============================] - 0s 873us/step - loss: 0.4369
Epoch 405/1000
8/8 

8/8 [==============================] - 0s 873us/step - loss: 0.4103
Epoch 492/1000
8/8 [==============================] - 0s 623us/step - loss: 0.4099
Epoch 493/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4096
Epoch 494/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4093
Epoch 495/1000
8/8 [==============================] - 0s 873us/step - loss: 0.4090
Epoch 496/1000
8/8 [==============================] - 0s 872us/step - loss: 0.4087
Epoch 497/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4084
Epoch 498/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4081
Epoch 499/1000
8/8 [==============================] - 0s 748us/step - loss: 0.4078
Epoch 500/1000
8/8 [==============================] - 0s 997us/step - loss: 0.4075
Epoch 501/1000
8/8 [==============================] - 0s 1ms/step - loss: 0.4072
Epoch 502/1000
8/8 [==============================] - 0s 747us/step - loss: 0.4068
Epoch 503/1000
8/8 [=

8/8 [==============================] - 0s 873us/step - loss: 0.3807
Epoch 590/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3803
Epoch 591/1000
8/8 [==============================] - 0s 623us/step - loss: 0.3800
Epoch 592/1000
8/8 [==============================] - 0s 999us/step - loss: 0.3798
Epoch 593/1000
8/8 [==============================] - 0s 623us/step - loss: 0.3794
Epoch 594/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3792
Epoch 595/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3789
Epoch 596/1000
8/8 [==============================] - 0s 1ms/step - loss: 0.3785
Epoch 597/1000
8/8 [==============================] - 0s 623us/step - loss: 0.3783
Epoch 598/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3780
Epoch 599/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3777
Epoch 600/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3774
Epoch 601/1000
8/8 [=

Epoch 688/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3525
Epoch 689/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3522
Epoch 690/1000
8/8 [==============================] - 0s 1ms/step - loss: 0.3520
Epoch 691/1000
8/8 [==============================] - 0s 623us/step - loss: 0.3517
Epoch 692/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3514
Epoch 693/1000
8/8 [==============================] - 0s 872us/step - loss: 0.3511
Epoch 694/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3509
Epoch 695/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3506
Epoch 696/1000
8/8 [==============================] - 0s 1ms/step - loss: 0.3503
Epoch 697/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3501
Epoch 698/1000
8/8 [==============================] - 0s 872us/step - loss: 0.3498
Epoch 699/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3495
Epoch 70

Epoch 787/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3265
Epoch 788/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3262
Epoch 789/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3260
Epoch 790/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3257
Epoch 791/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3254
Epoch 792/1000
8/8 [==============================] - 0s 623us/step - loss: 0.3252
Epoch 793/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3249
Epoch 794/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3247
Epoch 795/1000
8/8 [==============================] - 0s 998us/step - loss: 0.3244
Epoch 796/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3242
Epoch 797/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3239
Epoch 798/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3237
Epoc

8/8 [==============================] - 0s 748us/step - loss: 0.3020
Epoch 886/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3017
Epoch 887/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3014
Epoch 888/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3012
Epoch 889/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3010
Epoch 890/1000
8/8 [==============================] - 0s 997us/step - loss: 0.3007
Epoch 891/1000
8/8 [==============================] - 0s 873us/step - loss: 0.3005
Epoch 892/1000
8/8 [==============================] - 0s 499us/step - loss: 0.3002
Epoch 893/1000
8/8 [==============================] - 0s 748us/step - loss: 0.3000
Epoch 894/1000
8/8 [==============================] - 0s 748us/step - loss: 0.2997
Epoch 895/1000
8/8 [==============================] - 0s 748us/step - loss: 0.2995
Epoch 896/1000
8/8 [==============================] - 0s 747us/step - loss: 0.2992
Epoch 897/1000
8/8 

Epoch 984/1000
8/8 [==============================] - 0s 997us/step - loss: 0.2778
Epoch 985/1000
8/8 [==============================] - 0s 748us/step - loss: 0.2776
Epoch 986/1000
8/8 [==============================] - 0s 997us/step - loss: 0.2773
Epoch 987/1000
8/8 [==============================] - 0s 873us/step - loss: 0.2771
Epoch 988/1000
8/8 [==============================] - 0s 748us/step - loss: 0.2768
Epoch 989/1000
8/8 [==============================] - 0s 997us/step - loss: 0.2766
Epoch 990/1000
8/8 [==============================] - 0s 748us/step - loss: 0.2764
Epoch 991/1000
8/8 [==============================] - 0s 748us/step - loss: 0.2761
Epoch 992/1000
8/8 [==============================] - 0s 625us/step - loss: 0.2759
Epoch 993/1000
8/8 [==============================] - 0s 996us/step - loss: 0.2757
Epoch 994/1000
8/8 [==============================] - 0s 873us/step - loss: 0.2754
Epoch 995/1000
8/8 [==============================] - 0s 997us/step - loss: 0.2752
Epoc

In [17]:
model.predict(vector_x)

array([[0.14951631, 0.3711894 , 0.16236857, 0.02247006, 0.31547886],
       [0.28945285, 0.33168852, 0.24208236, 0.03274587, 0.13238373],
       [0.04109111, 0.27541596, 0.06786254, 0.04796332, 0.5330524 ],
       [0.01952741, 0.02957016, 0.02678776, 0.8671729 , 0.086261  ],
       [0.20376176, 0.36183462, 0.20037988, 0.03779319, 0.26217967],
       [0.28945285, 0.33168852, 0.24208236, 0.03274587, 0.13238373],
       [0.05871505, 0.26744828, 0.08602154, 0.07926154, 0.46813327],
       [0.02817446, 0.02843565, 0.03436095, 0.91773283, 0.06784904]],
      dtype=float32)

In [18]:
[list(vectorizer.vocabulary_.keys())[0]]

['i']

In [19]:
vectorizer.transform([list(vectorizer.vocabulary_.keys())[1]]).toarray()

array([[0, 0, 1, 0, 0]], dtype=int64)

Extract the word vectors by fetching the intermediate layer values where the inputs are the vectors of each individual word.

In [20]:
from keras.models import Model
layer_name = 'dense_1'
intermediate_layer_model = Model(inputs=model.input, outputs=model.get_layer(layer_name).output)

we are extracting the output of intermediate layer when we pass the one-hot-encoded version of the word as input.

In [21]:
for i in range(len(vectorizer.vocabulary_)):
    word = list(vectorizer.vocabulary_.keys())[i]
    word_vec = vectorizer.transform([list(vectorizer.vocabulary_.keys())[i]]).toarray()
    print(word, '\t', intermediate_layer_model.predict(word_vec))

i 	 [[-0.2700487  -0.96283925 -1.2158669 ]]
like 	 [[-0.94251233 -1.7060497  -0.78971237]]
watching 	 [[ 0.763609   -0.28392664 -1.2125309 ]]
movie 	 [[ 0.9979939 -1.6748781  1.0388861]]
enjoy 	 [[-0.91909295 -1.2099652  -0.9084841 ]]


# Measuring similarity between word vectors

In [22]:
a = word = list(vectorizer.vocabulary_.keys())[1]
word_vec_a = intermediate_layer_model.predict(vectorizer.transform([list(vectorizer.vocabulary_.keys())[1]]).toarray())

b = word = list(vectorizer.vocabulary_.keys())[4]
word_vec_b = intermediate_layer_model.predict(vectorizer.transform([list(vectorizer.vocabulary_.keys())[4]]).toarray())

In [23]:
a

'like'

In [24]:
b

'enjoy'

In [25]:
word_vec_a

array([[-0.94251233, -1.7060497 , -0.78971237]], dtype=float32)

In [26]:
word_vec_b

array([[-0.91909295, -1.2099652 , -0.9084841 ]], dtype=float32)

similarity = A.B/||A||2||B||2

In [27]:
np.sum(word_vec_a*word_vec_b)/((np.sqrt(np.sum(np.square(word_vec_a))))*np.sqrt(np.sum(np.square(word_vec_b))))

0.9798423

The Eucledian distance between two different vectors, A and B, is calculated as follows

distance = sqrt(A-B)^2

In [28]:
np.sum(np.square(word_vec_a - word_vec_b))

0.26075497